iteration_num: 60
batch_size: 1
data_parallel_size: 4
devoid_duplication: false
llm_model: "deepseek-ai/DeepSeek-V3.2"
timeout: 5000
data_dir: "../../datasets/cryptography-ascon/train"
project: "EasySAT/"
optimize_tasks:
  - "bump_var_function"
  - "restart_condition"
  - "restart_function"
  - "rephase_function"
task_selection_mode: "cycle"
original: true
original_result: {'time': 0, 'PAR-2': 1}
eval_baseline: true
run_id: ""
resume_from_checkpoint: false
checkpoint_dir: "./results/checkpoints"
checkpoint_path: ""
temperature: 0.9

api_base: "https://api.deepinfra.com/v1/openai"
api_key: ""

SAT_solver_file_path: './examples/EasySAT/original_EasySAT/EasySAT.cpp'
eval_timeout: 5000
results_save_path: './temp/eval_results/'
eval_data_dir: "../../datasets/cryptography-ascon/eval"
eval_parallel_size: 6
rand_seed: 42
keep_intermediate_results: False
model_name: 'deepseek-ai/DeepSeek-V3.2'
