iteration_num: 20
batch_size: 1
data_parallel_size: 6
devoid_duplication: false
timeout: 5000
data_dir: "../../datasets/Zamkeller/train"
project: "EasySAT/"
optimize_tasks:
  - "bump_var_function"
  - "restart_condition"
  - "restart_function"
task_selection_mode: "random_one"
original: false
original_result: {'time': 0, 'PAR-2': 1}
eval_baseline: false
eval_only_from_run: false
run_id: ""
resume_from_checkpoint: true
checkpoint_dir: "./results/checkpoints"
checkpoint_path: ""

SAT_solver_file_path: './examples/EasySAT/original_EasySAT/EasySAT.cpp'
eval_timeout: 5000
results_save_path: './temp/eval_results/'
eval_data_dir: "../../datasets/Zamkeller/eval"
eval_parallel_size: 6
temperature: 0.6
rand_seed: 42
keep_intermediate_results: False
