# EVAL-ONLY CONFIG FOR EXISTING RUN
iteration_num: 0
batch_size: 1
data_parallel_size: 1
devoid_duplication: false
timeout: 5000
data_dir: ""
project: ""
original: true
original_result: {'time': 0, 'PAR-2': 1}
eval_baseline: true
run_id: "20260417_231038_228638_5e00124e"
resume_from_checkpoint: false
checkpoint_dir: "./results/checkpoints"
checkpoint_path: ""

# Путь к SAT_solver_file_path из нужного run (eval будет брать этот файл)
SAT_solver_file_path: './results/runs/run_20260417_231038_228638_5e00124e/eval_results/tmp_d04_20_h23m50/SAT_Solver_tmp.cpp'
eval_timeout: 5000
results_save_path: './results/runs/run_20260417_231038_228638_5e00124e/eval_results/'
eval_data_dir: "../../datasets/cryptography-ascon/eval"
eval_parallel_size: 6
rand_seed: 42
keep_intermediate_results: False
